title: Harry Latch
logo: /assets/img/logo.png
description: Lo-fidelity Publishing and Social Ecology
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
